version: "3.1"
services:
  nginx:
    image: nginx:1.17-alpine
    container_name: e-station_api-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - e-station_api

  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./docker
      dockerfile: /php-fpm/Dockerfile
    image: e-station_api
    container_name: e-station_api-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - e-station_api

  db:
    image: mysql:5.7
    container_name: e-station_api-db
    restart: unless-stopped
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: e-station
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
      MYSQL_USER: user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - .mysqldata:/var/lib/mysql
    networks:
      - e-station_api

networks:
  e-station_api:
    driver: bridge
